### ISSUE TITLE
[Bug]:  Android: AudioPlaybackDemo isn't working on Android 10+

### ISSUE THREAD

**Issue by nofishonfriday** [juce-framework/JUCE#1089]
### Detailed steps on how to reproduce the bug

Build the AudioPlaybackDemo project for Android and execute it on a device which runs Android 10+ (API 29+). 
Result: `createInputStream()` returns `false`.

JUCE forum reference: [link](https://forum.juce.com/t/audioplaybackdemo-is-not-loading-files-permission-denied/36276)

I believe this is due to the fact that in Android 10 the way to access files has changed, please see my post [here](https://forum.juce.com/t/audioplaybackdemo-is-not-loading-files-permission-denied/36276/6) in the linked thread.

### What is the expected behaviour?

The choosen audio files plays.

### Operating systems

Android

### What versions of the operating systems?

10+

### Architectures

ARM

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by nofishonfriday** [comment]
Looks like it would need to be updated to use the [AndroidDocument](https://docs.juce.com/develop/classAndroidDocument.html) class to work with Android 10+.

**Comment by reuk** [comment]
I believe this was fixed in https://github.com/juce-framework/juce/commit/f46b94b6ff2a128d4b1dacc12f4efaef5ab01f46

**Comment by nofishonfriday** [comment]
Hi @reuk,

sorry for the late feedback.
Unfortunately the (unmodified) AudioPlaybackDemo is still not working for me in Android Studio (Windows) on current JUCE development branch (https://github.com/juce-framework/JUCE/commit/3816b095a8b6051521613baec8923392dfa669fc).
It now triggers an assertion when trying to open an audio file (not sure if related to the original issue though, I could also open a new issue for it, if preferred.)

![assert](https://user-images.githubusercontent.com/7658194/220999099-97087334-53bd-4cc3-a742-9f6ca2c38310.gif)

**Comment by reuk** [comment]
I'm guessing that `AndroidDocument::fromDocument` is failing for some reason, but I can't think why. If you stick a breakpoint in that function, can you find out which branch it takes?

**Comment by reuk** [comment]
It might also be helpful to see the output of logcat just before the assertion is hit, just in case any Java exceptions have been raised.

**Comment by nofishonfriday** [comment]
Thanks for the reply.
Here's stepping through (stepping 'over' actually, as too much calls to show with 'stepping into') from `AndroidDocument::fromDocument` until assert trigger.
![fromDocument](https://user-images.githubusercontent.com/7658194/221011737-4978830e-2f75-49e3-a5e0-692c95447bbb.gif)

And here's a logcat (as I'm quite new to Android dev I had to google how to do it lol, hope it's useful.)
[AudioPlaybackDemo logcat.txt](https://github.com/juce-framework/JUCE/files/10817866/AudioPlaybackDemo.logcat.txt)

**Comment by nofishonfriday** [comment]
Thanks @reuk.

While you are tweaking the AudioPlaybackDemo for Android, maybe take also this into consideration?
https://forum.juce.com/t/unmodified-exported-android-project-triggers-assertion/55099

(I don't understand why an Audio playback demo wants permission to _record_ audio anyway... :))

**Comment by reuk** [comment]
The demo has now been updated, removing mp3 support and adding flac support to the file chooser:

https://github.com/juce-framework/JUCE/commit/8b708b348d44ab47b2bdefcba41d27d02a2b413c

**Comment by nofishonfriday** [comment]
It now works out of the box with flac files. Thanks!
