### ISSUE TITLE
[Bug]: Audio/MIDI Settings window doesn't show up or shows up momentarily and disappears

### ISSUE THREAD

**Issue by wupeka** [juce-framework/JUCE#1242]
### Detailed steps on how to reproduce the bug

1. Launch standalone Dexed or Surge XT
2. Click "Options" -> "Audio/MIDI Settings..."
3. Settings window either doesn't show up at all (Surge XT) or sometimes shows up for a split second and disappears (Dexed)

Note that when I launch the app in WM-less Xnest the window shows up properly (without any decorations obviously)
Tested on Dexed "main", Surge XT "main" and Surge XT "main" with JUCE updated to "devel" branch.

### What is the expected behaviour?

Settings window shows up

### Operating systems

Linux

### What versions of the operating systems?

Ubuntu 23.04

### Architectures

x86_64

### Plug-in formats (if applicable)

Standalone

### Testing on the `develop` branch

The bug is present on the `develop` branch

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by BaraMGB** [comment]
I can reproduce this issue only on Ubuntu 23.04. Ubuntu 22.04 works fine. On 23.04 I have several problems. You can test it with the DemoRunner example (Dialog demo). Most of the dialog windows don't show up. Also popup menues doesn't show up most of the time.

I have tested on a AMD64 system (Geekom Air mini11) on wayland. By starting the DemoRunner app it crashes the entire window manager and brings me into the login screen.

I have tested on Aarch64 (Mac Mini M1 with native Ubuntu 23.04 per : [UbuntuAsahi](https://github.com/UbuntuAsahi/ubuntu-asahi). No popup menues, no dialog windows at least on wayland. 

I don't know, what is the difference between 22.04 and 23.04. Maybe the wayland server changend.

**Comment by reuk** [comment]
Thanks for reporting. I think this should be fixed here: https://github.com/juce-framework/JUCE/commit/f8d38edcd412d96534cc18058437818b5232356e

**Comment by razcore-rad** [comment]
I still experience this issue with latest Surge XT release 1.3.1 (2024-02-06 16:12:07 UTC ) which should incorporate the fix to this.
Thanks!

# Operating systems
Linux

# What versions of the operating systems?
Ubuntu 23.10 Linux 6.5.0-25-generic X11

# Architectures
x86_64

Stacktrace
No response

# Plug-in formats (if applicable)
Standalone

# Plug-in host applications (DAWs) (if applicable)
No response

# Testing on the develop branch
No
